name: Docker continuous integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    # schedule:
    #   - cron: '0 * * * *'
env:
  ARTIFACT_NAME: 'linux-amd64-default'
  DOCKER_IMAGE_NAME: 'app'
  DOCKER_IMAGE_TAG: 'latest'
jobs:
  builder:
    name: Builder
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master-fake'
    steps:
      - name: Fetch source code
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - name: Build and publish docker image
        uses: VaultVulp/gp-docker-action@1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ env.DOCKER_IMAGE_NAME }}
          image-tag: ${{ env.DOCKER_IMAGE_TAG }}
